# Generated by Django 3.1.5 on 2021-01-20 01:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_auto_20210119_1604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='plated_end_at',
            field=models.DateTimeField(validators=[django.core.validators.RegexValidator(message='The format of Date field should be: yyy-mm-dd', regex='^\\d{4}\\-(0?[1-9]|1[012])\\-(0?[1-9]|[12][0-9]|3[01])$')]),
        ),
    ]
